<h2>Types of ML Classification Algorithms:</h2>

Classification Algorithms can be further divided into the Mainly two category:

<h3>Linear Models</h3>

1. Logistic Regression
2. Support Vector Machines

<h3>Non-linear Models</h3>

1. K-Nearest Neighbours
2. Kernel SVM
3. Naïve Bayes
4. Decision Tree Classification
5. Random Forest Classification

In [166]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [167]:
data = pd.read_csv('/Users/snehvora/Desktop/Machine Learning/diabetes.csv')
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [168]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [169]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.6)

BY USING LINEAR REGRESSION PROVIDED IN SKLEARN 

In [170]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [171]:
from sklearn.linear_model import LogisticRegression  
classifier= LogisticRegression(random_state=0)  
classifier.fit(x_train, y_train)  

LogisticRegression(random_state=0)

In [172]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,

In [173]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test,y_pred)  
cm

array([[180,  19],
       [ 49,  60]])

USING PYTORCH 

In [174]:
import torch.nn as nn
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import TensorDataset
import torch

In [175]:
x_train = torch.from_numpy(x_train)
y_train = torch.from_numpy(y_train)

In [176]:
data = TensorDataset(x_train,y_train)
data_loader = DataLoader(data,batch_size=100)
data_loader

<h2>Log Loss or Cross-Entropy Loss:</h2>

Loss = -(ylog(p)+(1-y)log(1-p))  

Where y= Actual output, p= predicted output.

In [177]:
import torch.nn.functional as F
loss_func = F.cross_entropy

In [178]:
class Model(nn.Module):
    def __init__(self,in_size,hidden_size,out_size):
        super().__init__()
        self.linear1 = nn.Linear(in_size,hidden_size)
        self.linear2 = nn.Linear(hidden_size,out_size)

    def forward(self,xb):
        xb = xb.view(xb.size(0),-1)
        out = self.linear1(xb)
        out = F.relu(out)
        out = self.linear2(out)
        return out

model = Model(in_size=8, hidden_size=4, out_size=2)

In [179]:
opt = torch.optim.Adam(model.parameters(),lr=0.001)

In [180]:
def fit(epochs,data_loader,model,loss_func,opt):
    batch_size = []
    batch_loss = []
    for epoch in range(epochs):
        for xb,yb in data_loader:
            batch_size.append(len(xb))
            out = model(xb.float())
            loss = loss_func(out,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            batch_loss.append(loss.item())
        sum1 = 0
        for a,b in zip(batch_loss,batch_size):
            sum1 += a*b
        print('Epoch :'+ str(epoch+1)+ '/' + str(epochs)+'  '+'Loss : '+ str(sum1/np.sum(batch_size)))
        batch_size = []
        batch_loss = []

epochs = 200

In [181]:
fit(epochs,data_loader,model,loss_func,opt)

Epoch :1/200  Loss : 0.6737306636312733
Epoch :2/200  Loss : 0.6688556101011194
Epoch :3/200  Loss : 0.664380757705025
Epoch :4/200  Loss : 0.6601488434750101
Epoch :5/200  Loss : 0.6560857425565305
Epoch :6/200  Loss : 0.652168139167454
Epoch :7/200  Loss : 0.6483415235643801
Epoch :8/200  Loss : 0.6445772673772729
Epoch :9/200  Loss : 0.6408765393754711
Epoch :10/200  Loss : 0.6372332054635753
Epoch :11/200  Loss : 0.6336146826329438
Epoch :12/200  Loss : 0.6300057691076527
Epoch :13/200  Loss : 0.626352336095727
Epoch :14/200  Loss : 0.6226265793261321
Epoch :15/200  Loss : 0.6188638495362323
Epoch :16/200  Loss : 0.615071283734363
Epoch :17/200  Loss : 0.6112958788871765
Epoch :18/200  Loss : 0.607498692429584
Epoch :19/200  Loss : 0.6036779388137485
Epoch :20/200  Loss : 0.5998406824858292
Epoch :21/200  Loss : 0.5959368166716202
Epoch :22/200  Loss : 0.5920635798703069
Epoch :23/200  Loss : 0.5882061201593151
Epoch :24/200  Loss : 0.5843486086181973
Epoch :25/200  Loss : 0.580472

In [182]:
x_test = torch.from_numpy(x_test)
y_test = torch.from_numpy(y_test)

y_pred = model(x_test.float())
_,preds = torch.max(y_pred,dim=1)

In [183]:
preds

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,

In [184]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,preds)
cm

array([[171,  28],
       [ 42,  67]])