In [ ]:
import numpy as np

In [ ]:
l=list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
numpy1=np.array(l)
print(numpy1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
for i in numpy1:
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
list1=[1,2.3,"Dog"]
for i in list1:
  print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>


In [ ]:
np1=np.array(list1)
np1

array(['1', '2.3', 'Dog'], dtype='<U32')

In [ ]:
for i in np1:
  print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
np1.dtype

dtype('<U32')

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
l=[1,2,3,4]
l*2  

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
l1=[]
for i in l1:
  l1.append(i*2)
l1

[]

In [ ]:
np2=np.arange(1,5)
np2*2

array([2, 4, 6, 8])

In [ ]:
np2**2

array([ 1,  4,  9, 16])

In [ ]:
np2+2

array([3, 4, 5, 6])

In [ ]:
2**np2

array([ 2,  4,  8, 16])

In [ ]:
np.sqrt(np2)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.sum(np2)

10

In [ ]:
np.abs(np2)

array([1, 2, 3, 4])

In [ ]:
np.exp(np2)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
c=np.array([1,-2.3,-3.7,-5])
np.floor(c)

array([ 1., -3., -4., -5.])

In [ ]:
np.ceil(c)

array([ 1., -2., -3., -5.])

In [ ]:
np.around([1.23,3.54,5.79],decimals=1)

array([1.2, 3.5, 5.8])

In [ ]:
np3=np.array([1,2,3,4,5,56])
np3[0]

1

In [ ]:
np3[-1]

56

In [ ]:
list(enumerate(np3))

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 56)]

In [ ]:
np3[2:5]

array([3, 4, 5])

In [ ]:
np3[:5]

array([1, 2, 3, 4, 5])

In [ ]:
np3[::2]

array([1, 3, 5])

In [ ]:
np3[::-1]

array([56,  5,  4,  3,  2,  1])

In [ ]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a=a.reshape(2,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.shape

(2, 6)

In [ ]:
a=a.reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a[1,1]

5

In [ ]:
a+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109],
       [110, 111, 112]])

In [ ]:
b=a.reshape(2,2,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
b=a.reshape(2,3,2)
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
b[0][1][0]

3

In [ ]:
np3

array([ 1,  2,  3,  4,  5, 56])

In [ ]:
a=a.reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a.sum(axis=0)

array([22, 26, 30])

In [ ]:
a.sum(axis=1)

array([ 6, 15, 24, 33])

In [ ]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [ ]:
a.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18],
       [22, 26, 30]])

In [ ]:
a.prod()

479001600

In [ ]:
c=np.array([1,2,3,4,5,6,7,8,9,10])
d=c>5
d

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
c[c>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
c[d]

array([ 6,  7,  8,  9, 10])

In [ ]:
a=np.random.randint(1,101,10)
a

array([36, 13, 67, 13,  3, 70, 28, 24, 89, 73])

In [ ]:
np.random.seed(123)
a=np.random.randint(1,101,10)
a

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [ ]:
a=np.arange(1,11)
np.random.shuffle(a)
a

array([ 7,  6,  8,  9,  3,  4,  2,  5, 10,  1])

In [ ]:
a.sort()

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])